### ISSUE TITLE
File not found when running integration tests on GitHub Actions

### ISSUE THREAD

**Issue by kiranvasudev** [databrickslabs/cicd-templates#41]
By default, in the onpush workflow, integration tests are first deployed as a job on Databricks and then launched as a job. 
https://github.com/databrickslabs/cicd-templates/blob/5cf90b3e861dc851fdd8e2595d9dbb92eb3bd986/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/onpush.yml#L50-L56

What I would like to do here is to directly execute the integration test on a specific cluster without deploying the test as a job on Databricks and executing the job.

To achieve this, I have removed:
```yaml
      - name: Deploy integration test
        run: |
          dbx deploy --jobs=<job_name>

      - name: Run integration test
        run: |
          dbx launch --job=<job_name> --trace

```
 and added into the workflow file (`onpush.yml`):
```yaml
      - name: Run integration test
        run: |
          dbx execute --cluster-id=<id> --job=<job_name> --requirements-file=unit-requirements.txt
```
When the GitHub action workflow is executed, it breaks at the `Run integration test` job, with the error:
```
FileNotFoundError: [Errno 2] No such file or directory: '.dbx/lock.json'
```
I understand that this file contains the execution context and hence is in the `.gitignore`. 

As a result, is there a way that an integration test can be run without deploying it as a job on Databricks?
